"""toppings up cashiers acc

Revision ID: 00b0c1067639
Revises: fb972bcb8ae1
Create Date: 2025-04-22 21:12:43.005894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b0c1067639'
down_revision: Union[str, None] = 'fb972bcb8ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toppings up cashiers acc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('replenishment_number', sa.String(length=50), nullable=False, comment='Номер пополнения'),
    sa.Column('cashier', sa.String(length=100), nullable=False, comment='Кассир'),
    sa.Column('creation_date', sa.Date(), nullable=False, comment='Дата создания'),
    sa.Column('creation_time', sa.Time(), nullable=False, comment='Время создания'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='Создал'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Сумма'),
    sa.Column('delete_indicator', sa.Boolean(), nullable=False, comment='Индикатор удаления'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toppings up cashiers acc')
    # ### end Alembic commands ###
