"""the costs

Revision ID: 0c0f58509e69
Revises: 96d8477e4719
Create Date: 2025-04-22 18:44:54.171310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0f58509e69'
down_revision: Union[str, None] = '96d8477e4719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('the costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expense', sa.Numeric(precision=10, scale=2), nullable=False, comment='Расход'),
    sa.Column('payment_method', sa.String(length=20), nullable=False, comment='Способ оплаты'),
    sa.Column('payment_source', sa.String(length=100), nullable=False, comment='Источник оплаты'),
    sa.Column('amount_rub', sa.Numeric(precision=10, scale=2), nullable=False, comment='Сумма руб'),
    sa.Column('comment', sa.String(length=255), nullable=False, comment='Комментарий'),
    sa.Column('created_date', sa.Date(), nullable=False, comment='Дата создания'),
    sa.Column('created_time', sa.Time(), nullable=False, comment='Время создания'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='Создал'),
    sa.Column('deletion_indicator', sa.Boolean(), nullable=False, comment='Индикатор удаления'),
    sa.Column('deleted_date', sa.Date(), nullable=True, comment='Дата удаления'),
    sa.Column('deleted_time', sa.Time(), nullable=True, comment='Время удаления'),
    sa.Column('deleted_by', sa.String(length=100), nullable=True, comment='Удалил'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('the costs')
    # ### end Alembic commands ###
