"""transfers of materials btw warehouses

Revision ID: 154fad2f876b
Revises: f1b997f425a7
Create Date: 2025-04-21 18:49:15.999524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '154fad2f876b'
down_revision: Union[str, None] = 'f1b997f425a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfers of materials between warehouses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transfer_number', sa.String(length=50), nullable=False, comment='Номер перевода'),
    sa.Column('transfer_date', sa.DateTime(), nullable=False, comment='Дата перевода'),
    sa.Column('transfer_time', sa.DateTime(), nullable=False, comment='Время перевода'),
    sa.Column('executed_by', sa.String(length=100), nullable=False, comment='Кто выполнил перевод'),
    sa.Column('from_warehouse', sa.String(length=100), nullable=False, comment='Из склада'),
    sa.Column('to_warehouse', sa.String(length=100), nullable=False, comment='В склад'),
    sa.Column('from_material', sa.String(length=100), nullable=False, comment='Из материала'),
    sa.Column('to_material', sa.String(length=100), nullable=False, comment='В материал'),
    sa.Column('quantity_kg', sa.Float(), nullable=False, comment='Количество (кг)'),
    sa.Column('material_cost', sa.Float(), nullable=False, comment='Стоимость переводимого материала'),
    sa.Column('planned_material_cost', sa.Float(), nullable=False, comment='Стоимость итогового материала по плану'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfers of materials between warehouses')
    # ### end Alembic commands ###
