"""the cashiers

Revision ID: 225fdb22b6bb
Revises: d89c63a42377
Create Date: 2025-04-22 21:03:22.597999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '225fdb22b6bb'
down_revision: Union[str, None] = 'd89c63a42377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('the cashiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cashier_name', sa.String(length=100), nullable=False, comment='Кассир'),
    sa.Column('cash_balance', sa.Numeric(precision=10, scale=2), nullable=False, comment='Остаток на кассире'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('the cashiers')
    # ### end Alembic commands ###
