"""texts reasons rejecting ship crf

Revision ID: 4cfb7ebef273
Revises: d5090328b748
Create Date: 2025-04-21 19:25:17.311054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cfb7ebef273'
down_revision: Union[str, None] = 'd5090328b748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts of the reasons for rejecting shipping certificates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('act_number', sa.String(length=50), nullable=False, comment='Номер акта'),
    sa.Column('rejection_reason_text', sa.String(length=255), nullable=False, comment='Текст причин отклонения'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='Создал'),
    sa.Column('creation_date', sa.Date(), nullable=False, comment='Дата создания'),
    sa.Column('creation_time', sa.Time(), nullable=False, comment='Время создания'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('texts of the reasons for rejecting shipping certificates')
    # ### end Alembic commands ###
