"""connection btw main and blockage wrhs

Revision ID: 4ded796a6a75
Revises: d92625d1af4c
Create Date: 2025-04-21 19:48:30.829676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ded796a6a75'
down_revision: Union[str, None] = 'd92625d1af4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection btw main and blockage wrhs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('main_warehouse', sa.String(length=100), nullable=False, comment='Склад основной'),
    sa.Column('contaminated_warehouse', sa.String(length=100), nullable=False, comment='Склад засор'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection btw main and blockage wrhs')
    # ### end Alembic commands ###
