"""applications payment shipping certificates

Revision ID: 55f60d500fd8
Revises: 4cfb7ebef273
Create Date: 2025-04-21 19:38:06.010071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f60d500fd8'
down_revision: Union[str, None] = '4cfb7ebef273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications payment shippings certificates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_number', sa.String(length=50), nullable=False, comment='Номер приложения'),
    sa.Column('act_number', sa.String(length=50), nullable=False, comment='Номер акта'),
    sa.Column('creation_date', sa.Date(), nullable=False, comment='Дата создания'),
    sa.Column('creation_time', sa.Time(), nullable=False, comment='Время создания'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='Создал'),
    sa.Column('issued_amount_rub', sa.Numeric(precision=10, scale=2), nullable=False, comment='Выданная сумма (руб)'),
    sa.Column('payment_method', sa.String(length=100), nullable=False, comment='Способ оплаты'),
    sa.Column('replenishment_account', sa.String(length=50), nullable=False, comment='Счет пополнения'),
    sa.Column('balance_at_receiving', sa.Numeric(precision=10, scale=2), nullable=False, comment='Остаток на момент получения суммы'),
    sa.Column('deletion_indicator', sa.Boolean(), nullable=False, comment='Индикатор удаления'),
    sa.Column('deletion_date', sa.Date(), nullable=True, comment='Дата удаления'),
    sa.Column('deletion_time', sa.Time(), nullable=True, comment='Время удаления'),
    sa.Column('deleted_by', sa.String(length=100), nullable=True, comment='Удалил'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications payment shippings certificates')
    # ### end Alembic commands ###
