"""current admission price

Revision ID: 73c0bdf10914
Revises: 960b72a7a8f8
Create Date: 2025-04-21 18:10:58.261034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c0bdf10914'
down_revision: Union[str, None] = '960b72a7a8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current admission prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material', sa.String(length=100), nullable=False, comment='Наименование материала'),
    sa.Column('current_price_cash', sa.Float(), nullable=False, comment='Актуальная цена (наличный расчет)'),
    sa.Column('current_price_cashless', sa.Float(), nullable=False, comment='Актуальная цена (безналичный расчет)'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current admission prices')
    # ### end Alembic commands ###
