"""text reasons rejects

Revision ID: 8fc312c8649d
Revises: 5ec9f8a27345
Create Date: 2025-04-21 17:10:40.372949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc312c8649d'
down_revision: Union[str, None] = '5ec9f8a27345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reasons_rejection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False, comment='ID связанного акта приема'),
    sa.Column('reason_text', sa.String(length=500), nullable=False, comment='Текст причины отклонения'),
    sa.Column('creator', sa.String(length=100), nullable=False, comment='Идентификатор создателя записи'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата и время создания записи'),
    sa.ForeignKeyConstraint(['act_id'], ['acceptance_certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reasons_rejection')
    # ### end Alembic commands ###
