"""applications payment

Revision ID: 960b72a7a8f8
Revises: 8fc312c8649d
Create Date: 2025-04-21 17:54:22.086162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960b72a7a8f8'
down_revision: Union[str, None] = '8fc312c8649d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application for payment of acceptance certificates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_number', sa.String(length=50), nullable=False, comment='Номер приложения'),
    sa.Column('act_number', sa.String(length=50), nullable=False, comment='Номер акта'),
    sa.Column('created_date', sa.Date(), nullable=False, comment='Дата создания'),
    sa.Column('created_time', sa.Time(), nullable=False, comment='Время создания'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='Создал'),
    sa.Column('issued_amount', sa.Float(), nullable=False, comment='Выданная сумма (руб)'),
    sa.Column('payment_method', sa.String(length=50), nullable=False, comment='Способ оплаты'),
    sa.Column('payment_source', sa.String(length=100), nullable=False, comment='Источник оплаты'),
    sa.Column('remaining_balance', sa.Float(), nullable=False, comment='Остаток на момент выдачи суммы'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Индикатор удаления'),
    sa.Column('deleted_date', sa.Date(), nullable=True, comment='Дата удаления'),
    sa.Column('deleted_time', sa.Time(), nullable=True, comment='Время удаления'),
    sa.Column('deleted_by', sa.String(length=100), nullable=True, comment='Удалил'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application for payment of acceptance certificates')
    # ### end Alembic commands ###
