"""relationship the main and return

Revision ID: 96d8477e4719
Revises: 4ded796a6a75
Create Date: 2025-04-22 18:26:35.335261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d8477e4719'
down_revision: Union[str, None] = '4ded796a6a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship btw main and return wrhs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('main_warehouse', sa.String(length=100), nullable=False, comment='Склад основной'),
    sa.Column('return_warehouse', sa.String(length=100), nullable=False, comment='Склад возврата'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship btw main and return wrhs')
    # ### end Alembic commands ###
