"""current accounts original

Revision ID: 9b3573d1652f
Revises: fdbe4e2eb1ad
Create Date: 2025-04-22 20:20:39.298933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3573d1652f'
down_revision: Union[str, None] = 'fdbe4e2eb1ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False, comment='Расчетный счет'),
    sa.Column('balance_on_account', sa.Numeric(precision=10, scale=2), nullable=False, comment='Остаток на расчетный счет'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current accounts')
    # ### end Alembic commands ###
