"""shipping certificates

Revision ID: a8ac1bdf0a44
Revises: 154fad2f876b
Create Date: 2025-04-21 19:00:04.231659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8ac1bdf0a44'
down_revision: Union[str, None] = '154fad2f876b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping certificates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('act_number', sa.String(length=50), nullable=False, comment='Номер акта'),
    sa.Column('creation_date', sa.Date(), nullable=False, comment='Дата создания'),
    sa.Column('creation_time', sa.Time(), nullable=False, comment='Время создания'),
    sa.Column('shipment_date', sa.DateTime(), nullable=False, comment='Дата отгрузки'),
    sa.Column('counterparty', sa.String(length=100), nullable=False, comment='Контрагент'),
    sa.Column('warehouse', sa.String(length=100), nullable=False, comment='Склад'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='Создал'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Статус'),
    sa.Column('rejection_reason', sa.String(length=200), nullable=False, comment='Причина отклонения (индикатор)'),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False, comment='Номер автомобиля'),
    sa.Column('deletion_indicator', sa.Boolean(), nullable=False, comment='Индикатор удаления'),
    sa.Column('planned_sum', sa.Float(), nullable=False, comment='Сумма по акту (план)'),
    sa.Column('actual_sum', sa.Float(), nullable=False, comment='Сумма по акту (факт)'),
    sa.Column('actual_balance', sa.Float(), nullable=False, comment='Остаток (факт)'),
    sa.Column('paid_status', sa.Boolean(), nullable=False, comment='Погасили (факт)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('acceptance_certificates', sa.Column('act_number', sa.Integer(), nullable=False, comment='Номер акта'))
    op.drop_column('acceptance_certificates', 'act_id')
    op.add_column('reasons_rejection', sa.Column('act_number', sa.Integer(), nullable=False, comment='ID связанного акта приема'))
    op.drop_constraint('reasons_rejection_act_id_fkey', 'reasons_rejection', type_='foreignkey')
    op.create_foreign_key(None, 'reasons_rejection', 'acceptance_certificates', ['act_number'], ['id'])
    op.drop_column('reasons_rejection', 'act_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reasons_rejection', sa.Column('act_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ID связанного акта приема'))
    op.drop_constraint(None, 'reasons_rejection', type_='foreignkey')
    op.create_foreign_key('reasons_rejection_act_id_fkey', 'reasons_rejection', 'acceptance_certificates', ['act_id'], ['id'])
    op.drop_column('reasons_rejection', 'act_number')
    op.add_column('acceptance_certificates', sa.Column('act_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Номер акта'))
    op.drop_column('acceptance_certificates', 'act_number')
    op.drop_table('shipping certificates')
    # ### end Alembic commands ###
