"""movement of funds

Revision ID: b37bb5a07724
Revises: 9b3573d1652f
Create Date: 2025-04-22 20:40:52.585525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37bb5a07724'
down_revision: Union[str, None] = '9b3573d1652f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movement of funds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transfer_number', sa.String(length=50), nullable=False, comment='Номер перевода'),
    sa.Column('donor_account_number', sa.String(length=50), nullable=False, comment='Расчетный счет донор'),
    sa.Column('recipient_account_number', sa.String(length=50), nullable=False, comment='Расчетный счет рецепиент'),
    sa.Column('creation_date', sa.Date(), nullable=False, comment='Дата создания'),
    sa.Column('creation_time', sa.Time(), nullable=False, comment='Время создания'),
    sa.Column('performed_by', sa.String(length=100), nullable=False, comment='Выполнил перевод'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Сумма'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movement of funds')
    # ### end Alembic commands ###
