"""manual replenishment

Revision ID: d89c63a42377
Revises: b37bb5a07724
Create Date: 2025-04-22 20:58:16.683532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd89c63a42377'
down_revision: Union[str, None] = 'b37bb5a07724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual replenishment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('replenishment_number', sa.String(length=50), nullable=False, comment='Номер пополнения'),
    sa.Column('account_number', sa.String(length=50), nullable=False, comment='Расчетный счет'),
    sa.Column('creation_date', sa.Date(), nullable=False, comment='Дата создания'),
    sa.Column('creation_time', sa.Time(), nullable=False, comment='Время создания'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='Создал'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Сумма'),
    sa.Column('delete_indicator', sa.Boolean(), nullable=False, comment='Индикатор удаления'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manual replenishment')
    # ### end Alembic commands ###
