"""stocks warehouses

Revision ID: d92625d1af4c
Revises: 55f60d500fd8
Create Date: 2025-04-21 19:44:51.228010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92625d1af4c'
down_revision: Union[str, None] = '55f60d500fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks in warehouses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse', sa.String(length=100), nullable=False, comment='Склад'),
    sa.Column('material', sa.String(length=100), nullable=False, comment='Материал'),
    sa.Column('quantity_kg', sa.Numeric(precision=10, scale=2), nullable=False, comment='Количество (кг)'),
    sa.Column('actual_cost', sa.Numeric(precision=10, scale=2), nullable=False, comment='Стоимость (факт)'),
    sa.Column('planned_cost', sa.Numeric(precision=10, scale=2), nullable=False, comment='Стоимость (план)'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks in warehouses')
    # ### end Alembic commands ###
