"""history of change caps

Revision ID: f1b997f425a7
Revises: 73c0bdf10914
Create Date: 2025-04-21 18:38:31.924009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b997f425a7'
down_revision: Union[str, None] = '73c0bdf10914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history of changes in caps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material', sa.String(length=100), nullable=False, comment='Наименование материала'),
    sa.Column('current_price_cash', sa.Float(), nullable=False, comment='Актуальная цена (наличный расчет)'),
    sa.Column('current_price_cashless', sa.Float(), nullable=False, comment='Актуальная цена (безналичный расчет)'),
    sa.Column('entered_by', sa.String(length=100), nullable=False, comment='Кто ввел данные'),
    sa.Column('entry_date', sa.DateTime(), nullable=False, comment='Дата ввода'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history of changes in caps')
    # ### end Alembic commands ###
