"""create acceptance certificates table

Revision ID: ff7ca2e8e8d2
Revises: 
Create Date: 2025-04-20 20:06:34.288944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff7ca2e8e8d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acceptance_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_number', sa.String(length=50), nullable=False, comment='Номер акта'),
    sa.Column('date_creation', sa.Date(), nullable=False, comment='Дата создания акта'),
    sa.Column('creation_time', sa.Time(), nullable=False, comment='Время создания акта'),
    sa.Column('date_admission', sa.DateTime(), nullable=False, comment='Дата поступления'),
    sa.Column('counterparty_name', sa.String(length=100), nullable=False, comment='Наименование контрагента'),
    sa.Column('storage', sa.String(length=50), nullable=False, comment='Склад'),
    sa.Column('created', sa.DateTime(), nullable=False, comment='Дата и время создания записи'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Статус акта'),
    sa.Column('reason_rejection', sa.String(length=200), nullable=True, comment='Причина отклонения'),
    sa.Column('deletion_indicator', sa.Boolean(), nullable=False, comment='Признак удаления'),
    sa.Column('amount_according_act_plan', sa.Numeric(precision=10, scale=2), nullable=False, comment='Сумма по акту (план)'),
    sa.Column('amount_according_act_fact', sa.Numeric(precision=10, scale=2), nullable=False, comment='Сумма по акту (факт)'),
    sa.Column('extinguished_fact', sa.Boolean(), nullable=False, comment='Факт погашения'),
    sa.Column('remainder_fact', sa.Numeric(precision=10, scale=2), nullable=False, comment='Остаток (факт)'),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acceptance_certificates')
    # ### end Alembic commands ###
